package vistas;

import com.cfs3.proyectopets.FichaCtr;
import com.cfs3.proyectopets.FichaDto;
import com.cfs3.proyectopets.MascotaCtr;
import com.cfs3.proyectopets.MascotaDto;
import com.cfs3.proyectopets.UsuarioCtr;
import com.cfs3.proyectopets.UsuarioDto;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class VistaPrincipal extends javax.swing.JFrame {

    private FichaCtr control = new FichaCtr();
    private UsuarioCtr controlU = new UsuarioCtr();
    private MascotaCtr controlM = new MascotaCtr();
    List<FichaDto> listaFicha = null;
    List<MascotaDto> listaMasco = null;
    List<UsuarioDto> listaUsu = null;
    UsuarioDto usuIngre = null;//usuario en sesion
    int inicio = 0;
    int fin = 7;
    int idMascoV = controlM.ultimaMascotaBD() + 1;//
    int idUsuarioV = controlU.ultimoUsuarioBD() + 1;//
    int idFichaV = control.ultimaFichaBD() + 1;//

    public VistaPrincipal() {

        initComponents();
        Toolkit mipantalla = Toolkit.getDefaultToolkit();

        Dimension pantalla = mipantalla.getScreenSize();

        int altura = pantalla.height;
        int ancho = pantalla.width;

        setLocation(ancho / 8, altura / 8);

        setTitle("PETS");

        Image miIcono = mipantalla.getImage("jelly.png");

        setIconImage(miIcono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel5 = new javax.swing.JPanel();
        jBotonBuscarMascota = new javax.swing.JButton();
        jBotonAdoptarMascota = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jBotonAdministrarUsuarios = new javax.swing.JButton();
        jBotonCargarMascotas = new javax.swing.JButton();
        jBotonAdministrarFichas1 = new javax.swing.JButton();
        jButtonPerdidos = new javax.swing.JButton();
        jButtonEncontrados = new javax.swing.JButton();
        jButtonTransito = new javax.swing.JButton();
        jButtonSolidario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();

        jButton8.setText("jButton5");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBotonBuscarMascota.setText("Buscame");
        jBotonBuscarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarMascotaActionPerformed(evt);
            }
        });

        jBotonAdoptarMascota.setText("Adoptame!");
        jBotonAdoptarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAdoptarMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBotonAdoptarMascota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotonBuscarMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jBotonAdoptarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBotonBuscarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBotonAdministrarUsuarios.setText("Ingreso usuario");
        jBotonAdministrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAdministrarUsuariosActionPerformed(evt);
            }
        });

        jBotonCargarMascotas.setText("Cargar mascotas");
        jBotonCargarMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCargarMascotasActionPerformed(evt);
            }
        });

        jBotonAdministrarFichas1.setText("Publicar");
        jBotonAdministrarFichas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAdministrarFichas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBotonAdministrarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBotonCargarMascotas, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jBotonAdministrarFichas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBotonAdministrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBotonAdministrarFichas1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBotonCargarMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        jButtonPerdidos.setText("Perdidos");
        jButtonPerdidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerdidosActionPerformed(evt);
            }
        });

        jButtonEncontrados.setText("Encontrados");
        jButtonEncontrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncontradosActionPerformed(evt);
            }
        });

        jButtonTransito.setText("Transito");
        jButtonTransito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransitoActionPerformed(evt);
            }
        });

        jButtonSolidario.setText("Ser solidario");
        jButtonSolidario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolidarioActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Publicidades");
        jLabel9.setAlignmentX(10.0F);
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setText(" ");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setBackground(new java.awt.Color(204, 255, 255));
        jLabel8.setText(" ");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel70.setBackground(new java.awt.Color(204, 255, 255));
        jLabel70.setText(" ");
        jLabel70.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText(" ");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setText(" ");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setBackground(new java.awt.Color(204, 255, 255));
        jLabel5.setText(" ");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setText(" ");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setText(" ");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel70, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButtonPerdidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTransito, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSolidario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(252, 252, 252)
                    .addComponent(jButton3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(796, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonEncontrados, jButtonPerdidos, jButtonSolidario, jButtonTransito});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel5, jPanel6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonPerdidos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTransito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSolidario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(180, 180, 180)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(180, 180, 180)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSolidarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolidarioActionPerformed
        listaFicha = control.getFichas("serSolidario");
        listaMasco = control.getListaMascotaFicha("SserSolidario");
        refrescarGrilla();
    }//GEN-LAST:event_jButtonSolidarioActionPerformed

    private void jButtonPerdidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerdidosActionPerformed
        listaFicha = control.getFichas("perdido");
        listaMasco = control.getListaMascotaFicha("perdido");
        refrescarGrilla();
    }//GEN-LAST:event_jButtonPerdidosActionPerformed

    private void jButtonEncontradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncontradosActionPerformed
        listaFicha = control.getFichas("encontrado");
        listaMasco = control.getListaMascotaFicha("encontrado");
        refrescarGrilla();
    }//GEN-LAST:event_jButtonEncontradosActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonTransitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransitoActionPerformed
        listaFicha = control.getFichas("transito");
        listaMasco = control.getListaMascotaFicha("transito");
        refrescarGrilla();
    }//GEN-LAST:event_jButtonTransitoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //siguiente
        if (fin + 8 <= listaFicha.size()) {
            /* Si el valor que esta en "fin" + 8 es igual o menor al largo de la lista de fichas*/
            fin = fin + 8;
            inicio = inicio + 8;
            this.refrescarGrilla();
        } else {
            if ((fin - listaFicha.size() <= 8) && (fin - listaFicha.size() > 0)) {
                /*verifico que el fin sea realmente el fin, y no pasarme  ej: fin = 15 , ListaFicha = 16  */
                fin = fin + (fin - listaFicha.size());
                inicio = inicio + (fin - listaFicha.size());
                this.refrescarGrilla();
            } else {
                System.out.println("edod");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Anterior
        if ((inicio - 8 >= 0) && (fin - 8 <= inicio)) {
            /* Verifico que el inicio no sea el 0 */
            inicio = inicio - 8;
            fin = fin - 8;
            this.refrescarGrilla();

        } else {
            if (fin - inicio < 0) {
                /*inicio = 1 fin= 8, debo reiniciar el listado */
                inicio = 0;
                fin = 7;
                this.refrescarGrilla();
            } else {
                System.out.println("edod");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBotonAdoptarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAdoptarMascotaActionPerformed
        listaFicha = control.getFichas("adopcion");
        listaMasco = control.getListaMascotaFicha("adopcion");
        refrescarGrilla();
    }//GEN-LAST:event_jBotonAdoptarMascotaActionPerformed

    private void jBotonAdministrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAdministrarUsuariosActionPerformed
        if (usuIngre == null) {//el usuario ingresa
            IngresoUsuario ingresoU = new IngresoUsuario();
            this.usuIngre = controlU.UsuarioConContrasenia(ingresoU.getUsuario(), ingresoU.getContrasenia());
            if (usuIngre == null) {
                JOptionPane.showMessageDialog(null, "El usuario y clave no se corresponden. Ingresélos nuevamente.");
            } else {
                JOptionPane.showMessageDialog(null, "El usuario y clave son correctos");
                ingresoU.dispose();
            }
        } else {
            //el usuario ya había ingresado y quiere modificar sus datos  
            CargarUsuario cargarUs = new CargarUsuario(usuIngre);
            cargarUs.setVisible(true);

            controlU.agregarUsuario(usuIngre.getIdUsuario(), cargarUs.getApellidoynombre(), cargarUs.getCorreo(), cargarUs.getContrasenia(), cargarUs.getDireccion(), cargarUs.getTelefono());
        }
    }//GEN-LAST:event_jBotonAdministrarUsuariosActionPerformed

    private void jBotonBuscarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarMascotaActionPerformed

        BuscarMascotas busqueda = new BuscarMascotas();
        busqueda.setVisible(rootPaneCheckingEnabled);
        String estadom = busqueda.getEstado();
        String tipom = busqueda.getTipo();
        String sexom = busqueda.getSexo();
        String colorm = busqueda.getColor();
        String descripcionm = busqueda.getDescripcion();
        listaFicha = control.getFichas(estadom, tipom, sexom, colorm, descripcionm);
        listaMasco = control.getListaMascotaFicha(estadom, tipom, sexom, colorm, descripcionm);
        refrescarGrilla();

    }//GEN-LAST:event_jBotonBuscarMascotaActionPerformed

    private void jBotonCargarMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCargarMascotasActionPerformed
        CargaMascota cargaM = new CargaMascota(String.valueOf(idMascoV));
        cargaM.setVisible(true);


    }//GEN-LAST:event_jBotonCargarMascotasActionPerformed

    private void jBotonAdministrarFichas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAdministrarFichas1ActionPerformed
        //carga una ficha nueva
        CargarFicha cargaF = new CargarFicha(idUsuarioV, idFichaV);//carga una mascota nueva
        cargaF.setVisible(true);


    }//GEN-LAST:event_jBotonAdministrarFichas1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    public List<Image> byteToImage() {

        //genera una lista de imagenes a partir de la lista de mascotas
        System.out.println("pasó por byteToImage1");
        List<Image> listIm = new ArrayList<>();
        //    listIm=null;
        Image fotoMasco;
        for (MascotaDto masco : listaMasco) {
            System.out.println("pasó por byteToImage2");
            System.out.println(masco.getNombImagen().toString());
            if (masco.getImagen() != null) {
                System.out.println("pasó por byteToImage3");
                fotoMasco = getToolkit().getImage(masco.getNombImagen());//guarda imagen
                fotoMasco = fotoMasco.getScaledInstance(110, 110, Image.SCALE_DEFAULT);//escala la imagen a la ventana
                listIm.add(fotoMasco);
                System.out.println("lista de fotos completa");
            } else {
                listIm = null;
                System.out.println("lista vacia de fotos");
            }
        }
        return listIm;
    }

    private void refrescarGrilla() {
        if (listaFicha.size() < 8) {
            fin = listaFicha.size();
        }
        System.out.println("pasó por refrescar1");
        List<Image> listaFotos = byteToImage();
        System.out.println("pasó por refrescar2");
       System.out.println("fihn " + fin);
        System.out.println("inicio"+ inicio);
        if (listaFotos != null) {
            
            for (int i = inicio; i < fin; i++) {
                System.out.println("esto es la I" + i);
                switch (i) {
                    case 0:
                        jLabel1.setIcon(new ImageIcon(listaFotos.get(i)));
                        break;
                    case 1:
                        jLabel2.setIcon(new ImageIcon(listaFotos.get(i)));
                        break;
                    case 2:
                        jLabel3.setIcon(new ImageIcon(listaFotos.get(i)));
                        break;
                    case 3:
                        jLabel4.setIcon(new ImageIcon(listaFotos.get(i)));
                        break;
                    case 4:
                        jLabel5.setIcon(new ImageIcon(listaFotos.get(i)));
                        break;
                    case 5:
                        jLabel6.setIcon(new ImageIcon(listaFotos.get(i)));
                        break;
                    case 6:
                        jLabel70.setIcon(new ImageIcon(listaFotos.get(i)));
                        break;
                    case 7:
                        jLabel8.setIcon(new ImageIcon(listaFotos.get(i)));
                        break;
                }
            }
        } else {
            System.out.println("No hay fotos para mostrar");
            JOptionPane.showMessageDialog(rootPane, "No hay fotos para mostrar.");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonAdministrarFichas1;
    private javax.swing.JButton jBotonAdministrarUsuarios;
    private javax.swing.JButton jBotonAdoptarMascota;
    private javax.swing.JButton jBotonBuscarMascota;
    private javax.swing.JButton jBotonCargarMascotas;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonEncontrados;
    private javax.swing.JButton jButtonPerdidos;
    private javax.swing.JButton jButtonSolidario;
    private javax.swing.JButton jButtonTransito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

}
