package com.cfs3.proyectopets;



import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * UsuarioDto generated by hbm2java
 */
public class UsuarioDto  implements java.io.Serializable {
 
     private int idUsuario;
     private String apellidoynombre;
     private String correo;
     private String contrasenia;
     private String direccion;
     private Integer telefono;
     private List<FichaDto> listaFichas=new ArrayList<>();

    public UsuarioDto() {
    }

	
    public UsuarioDto(int idUsuario, String apellidoynombre, String correo, String contrasenia) {
        this.idUsuario = idUsuario;
        this.apellidoynombre = apellidoynombre;
        this.correo = correo;
        this.contrasenia = contrasenia;
        
    }
    public UsuarioDto(int idUsuario, String apellidoynombre, String correo, String contrasenia, String direccion, Integer telefono) {
       this.idUsuario = idUsuario;
       this.apellidoynombre = apellidoynombre;
       this.correo = correo;
       this.contrasenia = contrasenia;
       this.direccion = direccion;
       this.telefono = telefono;
       
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getApellidoynombre() {
        return this.apellidoynombre;
    }
    
    public void setApellidoynombre(String apellidoynombre) {
        this.apellidoynombre = apellidoynombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public List<FichaDto> getListaFichas() {
        return this.listaFichas;
    }
    
    public void setListaFichas(List<FichaDto> listFichas) {
        this.listaFichas = listFichas;
    }




}


